"use client";

import { Check, Clock, Flame, Plus } from "lucide-react";
import type { Recipe } from "@/lib/kitchen/types";

interface RecipeCardProps { recipe: Recipe; orderedBy: string[]; currentMember: string; onView: (recipe: Recipe) => void; onToggle: (recipe: Recipe) => void; }
/** 菜谱卡片，包含详情入口和点菜按钮。 */
export function RecipeCard({ recipe, orderedBy, currentMember, onView, onToggle }: RecipeCardProps) {
  const isOrderedByAnyone = orderedBy.length > 0; const isOrderedByMe = orderedBy.includes(currentMember);
  return <div className={`group bg-white rounded-2xl border transition-all duration-200 overflow-hidden flex flex-col justify-between ${isOrderedByAnyone ? "border-orange-300 ring-1 ring-orange-200 shadow-xs" : "border-stone-200 hover:border-stone-300 hover:shadow-xs"}`}><div onClick={() => onView(recipe)} className="p-4 cursor-pointer flex-1"><div className="flex items-start justify-between gap-2 mb-1.5"><h4 className="font-bold text-stone-900 group-hover:text-orange-600 transition-colors">{recipe.name}</h4><span className="text-[11px] px-2 py-0.5 rounded-md bg-stone-100 text-stone-600 font-medium whitespace-nowrap">{recipe.category}</span></div>{recipe.description && <p className="text-xs text-stone-500 line-clamp-2 mb-3">{recipe.description}</p>}<div className="flex flex-wrap gap-1 mb-2">{recipe.ingredients.slice(0, 4).map((ing, index) => <span key={index} className="text-[11px] px-1.5 py-0.5 bg-stone-50 text-stone-600 rounded border border-stone-100">{ing.name} {ing.quantity ? `${ing.quantity}${ing.unit}` : ing.unit}</span>)}{recipe.ingredients.length > 4 && <span className="text-[11px] text-stone-400 px-1 py-0.5">+{recipe.ingredients.length - 4}样</span>}</div><div className="flex items-center gap-3 text-[11px] text-stone-400">{recipe.prep_time && <span className="flex items-center gap-1"><Clock className="w-3 h-3" />{recipe.prep_time}</span>}{recipe.difficulty && <span className="flex items-center gap-1"><Flame className="w-3 h-3 text-amber-500" />{recipe.difficulty}</span>}</div></div><div className="px-4 py-2.5 bg-stone-50/80 border-t border-stone-100 flex items-center justify-between"><div className="flex items-center gap-1 text-xs">{isOrderedByAnyone ? <div className="flex items-center gap-1 flex-wrap"><span className="text-orange-700 font-semibold">已选：</span>{orderedBy.map((user, index) => <span key={index} className="px-1.5 py-0.5 rounded bg-orange-100 text-orange-800 text-[10px] font-medium">{user}</span>)}</div> : <span className="text-stone-400">尚未加入菜单</span>}</div><button id={`btn-order-${recipe.id}`} onClick={() => onToggle(recipe)} className={`inline-flex items-center gap-1 px-3 py-1.5 rounded-xl text-xs font-semibold transition-all ${isOrderedByMe ? "bg-orange-600 text-white shadow-xs hover:bg-orange-700" : isOrderedByAnyone ? "bg-orange-100 text-orange-800 hover:bg-orange-200 border border-orange-300" : "bg-stone-900 text-white hover:bg-black"}`}>{isOrderedByMe ? <><Check className="w-3.5 h-3.5" /><span>我也想吃 (已点)</span></> : <><Plus className="w-3.5 h-3.5" /><span>{isOrderedByAnyone ? "我也想吃 +1" : "我想吃这道"}</span></>}</button></div></div>;
}
