import { Recipe } from "./types";

export const DEFAULT_RECIPES: Recipe[] = [
  {
    id: "recipe-tomato-egg",
    name: "番茄炒鸡蛋",
    category: "热菜",
    description: "酸甜多汁，蛋香浓郁，最经典的家常快手菜",
    prep_time: "10分钟",
    difficulty: "简单",
    ingredients: [
      { name: "番茄", quantity: 2, unit: "个", note: "成熟多汁为佳，切滚刀块" },
      { name: "鸡蛋", quantity: 3, unit: "个", note: "加少许盐打散" },
      { name: "大蒜", quantity: 2, unit: "瓣", note: "切末" },
      { name: "小葱", quantity: 1, unit: "根", note: "切葱花" },
      { name: "白糖", quantity: 1, unit: "茶匙", note: "中和酸味提鲜" },
      { name: "食用盐", quantity: 3, unit: "克", note: "适量" },
      { name: "食用油", quantity: 20, unit: "ml", note: "适量" },
    ],
    steps: [
      {
        step: 1,
        title: "处理食材",
        content: "番茄洗净切小块（可开水烫去皮）；鸡蛋打入碗中，加入少许盐和几滴水搅拌均匀。",
        tip: "蛋液里加少许水炒出来更蓬松软嫩。",
      },
      {
        step: 2,
        title: "滑炒鸡蛋",
        content: "热锅倒油，油温七成热时倒入蛋液，用铲子快速划散炒成大块，凝固即可盛出备用。",
        tip: "鸡蛋不要炒太久，刚凝固就盛出，保持鲜嫩。",
      },
      {
        step: 3,
        title: "翻炒番茄出汁",
        content: "锅底留少许底油，下入蒜末爆香，加入番茄块中火翻炒，加入1茶匙白糖，炒至番茄出浓郁红汁。",
        tip: "用铲子轻压番茄块帮助快速出汁。",
      },
      {
        step: 4,
        title: "混合调味出锅",
        content: "倒入炒好的鸡蛋块，加入适量盐，大火快速翻炒均匀吸收汤汁，撒上葱花即可出锅。",
        tip: "汤汁拌饭非常香！",
      },
    ],
  },
  {
    id: "recipe-fried-eggplant",
    name: "炒茄子",
    category: "热菜",
    description: "蒜香扑鼻，软糯入味，家常下饭绝配",
    prep_time: "15分钟",
    difficulty: "简单",
    ingredients: [
      { name: "茄子", quantity: 2, unit: "根", note: "圆茄或长茄均可，切条" },
      { name: "大蒜", quantity: 4, unit: "瓣", note: "切蒜末" },
      { name: "青椒", quantity: 1, unit: "个", note: "切丝" },
      { name: "生抽", quantity: 2, unit: "勺", note: "调味" },
      { name: "蚝油", quantity: 1, unit: "勺", note: "提鲜" },
      { name: "食用盐", quantity: 2, unit: "克", note: "杀水与调味" },
      { name: "食用油", quantity: 20, unit: "ml", note: "适量" },
    ],
    steps: [
      {
        step: 1,
        title: "茄子杀水去涩",
        content: "茄子洗净切成长条，撒入少量盐抓匀腌制10分钟，杀出黑水后用手挤干水分备用。",
        tip: "提前杀水能大大减少茄子的吸油量，健康不油腻。",
      },
      {
        step: 2,
        title: "调制碗汁",
        content: "小碗中加入2勺生抽、1勺蚝油、半勺糖、少许水淀粉搅拌均匀调成酱汁备用。",
      },
      {
        step: 3,
        title: "煸炒茄子",
        content: "锅中倒油加热，先下入挤干水分的茄子条，中小火煸炒至茄子变软透明微焦。",
      },
      {
        step: 4,
        title: "加蒜炝锅入味",
        content: "下入大半蒜末和青椒丝翻炒出蒜香味，淋入调好的料汁大火翻炒包裹均匀，出锅前撒入剩余蒜末翻两下即可。",
        tip: "出锅前再放一把生蒜末是蒜香浓郁的关键秘诀！",
      },
    ],
  },
  {
    id: "recipe-pork-pepper",
    name: "青椒肉丝",
    category: "热菜",
    description: "肉丝滑嫩，青椒爽脆，咸香适口",
    prep_time: "15分钟",
    difficulty: "中等",
    ingredients: [
      { name: "猪里脊肉", quantity: 200, unit: "克", note: "顺纹切细丝" },
      { name: "青椒", quantity: 3, unit: "个", note: "去籽切丝" },
      { name: "大蒜", quantity: 2, unit: "瓣", note: "切碎" },
      { name: "生姜", quantity: 5, unit: "克", note: "切丝" },
      { name: "生抽", quantity: 2, unit: "勺", note: "腌肉及调味" },
      { name: "料酒", quantity: 1, unit: "勺", note: "去腥" },
      { name: "玉米淀粉", quantity: 1, unit: "勺", note: "上浆" },
      { name: "食用油", quantity: 25, unit: "ml", note: "适量" },
    ],
    steps: [
      {
        step: 1,
        title: "肉丝上浆腌制",
        content: "里脊肉切细丝，加1勺生抽、1勺料酒、半勺淀粉、少许清水抓匀至发粘，最后封上一勺食用油锁水，腌制10分钟。",
        tip: "最后封油可以防止下锅粘连，让肉丝极滑嫩。",
      },
      {
        step: 2,
        title: "滑炒肉丝",
        content: "热锅凉油，下入腌好的肉丝快速划散，变色至八成熟即刻盛出备用。",
      },
      {
        step: 3,
        title: "煸炒青椒",
        content: "锅留底油，下姜丝、蒜末爆香，倒入青椒丝大火翻炒至断生且稍微起虎皮。",
      },
      {
        step: 4,
        title: "合炒出锅",
        content: "倒入滑好的肉丝，加1勺生抽、少许盐，大火快速翻炒15秒均匀入味，出锅装盘。",
      },
    ],
  },
  {
    id: "recipe-potato-strips",
    name: "酸辣土豆丝",
    category: "素菜",
    description: "根根爽脆，酸辣开胃，百吃不厌",
    prep_time: "12分钟",
    difficulty: "简单",
    ingredients: [
      { name: "土豆", quantity: 2, unit: "个", note: "去皮切细丝" },
      { name: "干辣椒", quantity: 4, unit: "个", note: "剪段" },
      { name: "花椒", quantity: 15, unit: "粒", note: "增香" },
      { name: "大蒜", quantity: 3, unit: "瓣", note: "切片" },
      { name: "白醋", quantity: 2, unit: "勺", note: "保脆调酸" },
      { name: "食用盐", quantity: 3, unit: "克", note: "适量" },
      { name: "食用油", quantity: 20, unit: "ml", note: "适量" },
    ],
    steps: [
      {
        step: 1,
        title: "切丝浸泡洗淀粉",
        content: "土豆去皮切成均匀细丝，放入清水中反复冲洗2-3遍，洗去表面多余淀粉并沥干水分。",
        tip: "多洗去淀粉是土豆丝爽脆不粘锅的关键。",
      },
      {
        step: 2,
        title: "炝香花椒与辣椒",
        content: "锅中热油，先下花椒粒小火炸出香味后捞出不要，再下干辣椒段和蒜片爆香。",
      },
      {
        step: 3,
        title: "大火快炒烹醋",
        content: "转大火倒入土豆丝快速翻炒半分钟，先顺锅边烹入1勺白醋锁住爽脆口感。",
        tip: "第一次烹醋保脆，第二次出锅前加醋提香。",
      },
      {
        step: 4,
        title: "二次调味出锅",
        content: "加入适量盐翻炒至土豆丝呈半透明状，出锅前再淋入第2勺白醋，翻炒均匀即出锅。",
      },
    ],
  },
  {
    id: "recipe-cola-wings",
    name: "可乐鸡翅",
    category: "荤菜",
    description: "色泽红亮，肉质鲜嫩多汁，孩子们的最爱",
    prep_time: "25分钟",
    difficulty: "简单",
    ingredients: [
      { name: "鸡中翅", quantity: 8, unit: "个", note: "两面划两刀" },
      { name: "可乐", quantity: 1, unit: "听", note: "约330ml（普通可乐非无糖）" },
      { name: "生姜", quantity: 10, unit: "克", note: "切片" },
      { name: "小葱", quantity: 2, unit: "根", note: "打结或切葱花" },
      { name: "料酒", quantity: 1, unit: "勺", note: "焯水去腥" },
      { name: "生抽", quantity: 2, unit: "勺", note: "咸鲜调味" },
      { name: "老抽", quantity: 1, unit: "勺", note: "上红亮色" },
      { name: "食用盐", quantity: 2, unit: "克", note: "调味" },
    ],
    steps: [
      {
        step: 1,
        title: "鸡翅改刀焯水",
        content: "鸡翅洗净正反各划两刀，冷水下锅加入葱结、姜片、1勺料酒，大火煮沸撇去浮沫，捞出用温水冲净并沥干水分。",
      },
      {
        step: 2,
        title: "煎至金黄",
        content: "平底锅少许油，下入鸡翅中小火慢煎，煎至两面金黄微焦出油。",
      },
      {
        step: 3,
        title: "倒入可乐焖煮",
        content: "下入姜片爆香，倒入1听可乐没过鸡翅，加入2勺生抽、1勺老抽和少许盐，大火烧开后转中小火盖盖焖煮15分钟。",
      },
      {
        step: 4,
        title: "大火浓缩收汁",
        content: "揭开锅盖转大火收汁，不断翻动鸡翅让浓郁汤汁均匀裹在鸡翅表面，汤汁粘稠即可出锅装盘撒熟芝麻或葱花。",
      },
    ],
  },
  {
    id: "recipe-braised-ribs",
    name: "红烧排骨",
    category: "荤菜",
    description: "酱香浓郁，肉烂脱骨，家庭聚餐硬菜",
    prep_time: "40分钟",
    difficulty: "中等",
    ingredients: [
      { name: "猪小排", quantity: 500, unit: "克", note: "剁成小段" },
      { name: "冰糖", quantity: 20, unit: "克", note: "炒糖色" },
      { name: "大蒜", quantity: 4, unit: "瓣", note: "拍扁" },
      { name: "生姜", quantity: 15, unit: "克", note: "切片" },
      { name: "八角", quantity: 2, unit: "个", note: "香料" },
      { name: "桂皮", quantity: 1, unit: "小块", note: "香料" },
      { name: "生抽", quantity: 2, unit: "勺", note: "调味" },
      { name: "老抽", quantity: 1, unit: "勺", note: "上色" },
      { name: "料酒", quantity: 2, unit: "勺", note: "去腥" },
      { name: "食用盐", quantity: 3, unit: "克", note: "最后调味" },
    ],
    steps: [
      {
        step: 1,
        title: "排骨冷水焯水",
        content: "排骨浸泡出血水后，冷水下锅加入料酒和姜片，大火煮沸撇净浮沫，捞出用温水洗净沥干备用。",
      },
      {
        step: 2,
        title: "炒糖色裹红亮",
        content: "热锅倒少量油，放入冰糖小火慢慢融化翻炒，炒至焦糖色冒微小气泡时，迅速倒入排骨翻炒上色均匀。",
        tip: "小火炒糖色防焦苦，下排骨前注意防油溅。",
      },
      {
        step: 3,
        title: "加香料加水焖炖",
        content: "加入葱姜蒜、八角、桂皮炒香，淋入生抽、老抽翻炒均匀，倒入没过排骨的开水，大火烧开后转小火盖盖焖炖30分钟。",
        tip: "炖肉务必加开水或热水，冷水会使肉质紧缩变柴。",
      },
      {
        step: 4,
        title: "加盐大火收汁",
        content: "排骨软烂后加入适量盐调味，转大火不断翻炒收干浓稠汤汁，直至酱汁红亮紧紧包裹排骨即可。",
      },
    ],
  },
  {
    id: "recipe-tomato-beef",
    name: "番茄炖牛腩",
    category: "荤菜",
    description: "汤浓味厚，牛腩软烂，酸爽开胃的暖心大菜",
    prep_time: "50分钟",
    difficulty: "中等",
    ingredients: [
      { name: "牛腩", quantity: 500, unit: "克", note: "切麻将块大小" },
      { name: "番茄", quantity: 3, unit: "个", note: "成熟红番茄，切块" },
      { name: "土豆", quantity: 1, unit: "个", note: "去皮滚刀块" },
      { name: "胡萝卜", quantity: 1, unit: "根", note: "切滚刀块" },
      { name: "洋葱", quantity: 0.5, unit: "个", note: "切块" },
      { name: "大蒜", quantity: 4, unit: "瓣", note: "拍扁" },
      { name: "生姜", quantity: 15, unit: "克", note: "切厚片" },
      { name: "番茄酱", quantity: 2, unit: "勺", note: "丰富酸香层次" },
      { name: "生抽", quantity: 2, unit: "勺", note: "调味" },
      { name: "食用盐", quantity: 5, unit: "克", note: "适量" },
    ],
    steps: [
      {
        step: 1,
        title: "牛腩焯水去血沫",
        content: "牛腩切块冷水浸泡半小时，冷水下锅加入姜片料酒煮开撇去浮沫，捞出温水冲洗干净。",
      },
      {
        step: 2,
        title: "先炒一半番茄与洋葱",
        content: "锅中热油下姜蒜、洋葱炒香，放入一半番茄块和2勺番茄酱大火煸炒至出浓稠红油沙汁。",
      },
      {
        step: 3,
        title: "下牛腩慢炖软烂",
        content: "倒入焯好的牛腩翻炒均匀，加入足量开水和2勺生抽，大火煮沸后转小火慢炖40分钟（或高压锅压20分钟）。",
      },
      {
        step: 4,
        title: "放入配菜与剩余番茄",
        content: "加入土豆块、胡萝卜块和剩下的一半番茄块，加入盐调味，继续小火炖煮15分钟至土豆软烂、汤汁浓稠即可。",
      },
    ],
  },
  {
    id: "recipe-green-veggies",
    name: "清炒菜心",
    category: "素菜",
    description: "碧绿脆嫩，清甜爽口，家庭必备解腻素菜",
    prep_time: "8分钟",
    difficulty: "简单",
    ingredients: [
      { name: "广东菜心", quantity: 400, unit: "克", note: "洗净摘除老根" },
      { name: "大蒜", quantity: 3, unit: "瓣", note: "切蒜末" },
      { name: "食用盐", quantity: 3, unit: "克", note: "适量" },
      { name: "食用油", quantity: 15, unit: "ml", note: "适量" },
    ],
    steps: [
      {
        step: 1,
        title: "洗净沥干",
        content: "菜心洗净沥干水分，较粗的菜茎部分可以用刀纵向划一刀方便熟透入味。",
      },
      {
        step: 2,
        title: "热油蒜爆香",
        content: "热锅倒油，下入蒜末小火爆出浓郁蒜香味。",
      },
      {
        step: 3,
        title: "大火快炒",
        content: "转大火先下入菜心茎部翻炒几下，再下入菜叶部分，大火快速翻炒1-2分钟至变色变软。",
      },
      {
        step: 4,
        title: "调味出锅",
        content: "加入适量食用盐，快速翻炒均匀即可盛盘，保持菜叶翠绿清脆。",
      },
    ],
  },
  {
    id: "recipe-tomato-egg-soup",
    name: "番茄蛋花汤",
    category: "汤羹",
    description: "酸香开胃，蛋花如丝，暖胃舒心",
    prep_time: "10分钟",
    difficulty: "简单",
    ingredients: [
      { name: "番茄", quantity: 1, unit: "个", note: "切小丁" },
      { name: "鸡蛋", quantity: 2, unit: "个", note: "打散成蛋液" },
      { name: "小葱", quantity: 1, unit: "根", note: "切葱花" },
      { name: "水淀粉", quantity: 2, unit: "勺", note: "勾薄芡" },
      { name: "香油", quantity: 1, unit: "茶匙", note: "出锅点缀" },
      { name: "食用盐", quantity: 3, unit: "克", note: "适量" },
    ],
    steps: [
      {
        step: 1,
        title: "炒番茄碎出红汤",
        content: "热锅少许油下葱白炒香，下番茄丁小火翻炒出红油沙汁，加入适量开水大火烧开。",
      },
      {
        step: 2,
        title: "勾薄芡调底味",
        content: "加入适量盐调味，淋入2勺水淀粉搅拌均匀让汤汁稍微变稠润，便于托起蛋花。",
      },
      {
        step: 3,
        title: "淋蛋液出漂亮蛋花",
        content: "转小火让汤水微沸，将打散的蛋液顺着筷子转圈细细淋入锅中，待蛋花浮起后轻轻推动锅铲。",
      },
      {
        step: 4,
        title: "淋香油撒葱花",
        content: "关火，淋入少许香油，撒上翠绿葱花即可出锅盛汤。",
      },
    ],
  },
];
